### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by 501st-alpha1** [marisks/blog#1]
I see that [your README](https://github.com/marisks/blog/blob/master/README.md) hasn't been customized from the default, and I can't find this info anywhere else, so I figured I'd ask here: how are you licensing the code in your blog posts?

I ask because I'd like to use some code (specifically from [Entity Framework: Soft Delete and automatic Created, Modified dates](http://marisks.net/2016/02/27/entity-framework-soft-delete-and-automatic-created-modified-dates/)) in a project.  It would actually be nice to be able to pull it in as a NuGet package instead.  I couldn't find one online, so if the license is compatible I'd be happy to create one myself.

**Comment by marisks** [comment]
I do not have license info yet on the blog. But I will add it - MIT license for all code on the blog (but not other content).

**Comment by marisks** [comment]
Fixed: https://github.com/marisks/blog/commit/2ddfc97bdc2eae582e3ca5c2a35afe04116df9a8
